// <auto-generated />
using Jornada.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jornada.Migrations
{
    [DbContext(typeof(JornadaDataContext))]
    [Migration("20260201195605_Migration0007")]
    partial class Migration0007
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jornada.Models.Depoimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Descricao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Depoimento", (string)null);
                });

            modelBuilder.Entity("Jornada.Models.DepoimentoFoto", b =>
                {
                    b.Property<int>("DepoimentoId")
                        .HasColumnType("int");

                    b.Property<int>("FotoId")
                        .HasColumnType("int");

                    b.HasKey("DepoimentoId", "FotoId");

                    b.HasIndex("FotoId");

                    b.ToTable("Depoimento_Foto", (string)null);
                });

            modelBuilder.Entity("Jornada.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Meta")
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Meta");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<int>("Preco")
                        .HasColumnType("INT")
                        .HasColumnName("Preco");

                    b.Property<string>("TextoDescritivo")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasColumnName("TextoDescritivo");

                    b.HasKey("Id");

                    b.ToTable("Destino", null, t =>
                        {
                            t.HasCheckConstraint("CK_Preco_Greather_Than_Zero", "[Preco] > 0");
                        });
                });

            modelBuilder.Entity("Jornada.Models.DestinoFoto", b =>
                {
                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<int>("FotoId")
                        .HasColumnType("int");

                    b.HasKey("DestinoId", "FotoId");

                    b.HasIndex("FotoId");

                    b.ToTable("Destino_Foto", (string)null);
                });

            modelBuilder.Entity("Jornada.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("Jornada.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Jornada.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("SenhaHash");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Usuario_Email")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRole");
                });

            modelBuilder.Entity("Jornada.Models.Depoimento", b =>
                {
                    b.HasOne("Jornada.Models.Usuario", "Usuario")
                        .WithMany("Depoimentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Depoimento_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Jornada.Models.DepoimentoFoto", b =>
                {
                    b.HasOne("Jornada.Models.Depoimento", "Depoimento")
                        .WithMany("DepoimentoFotos")
                        .HasForeignKey("DepoimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jornada.Models.Foto", "Foto")
                        .WithMany("DepoimentoFotos")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Depoimento");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("Jornada.Models.DestinoFoto", b =>
                {
                    b.HasOne("Jornada.Models.Destino", "Destino")
                        .WithMany("DestinoFotos")
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jornada.Models.Foto", "Foto")
                        .WithMany("DestinoFotos")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("UsuarioRole", b =>
                {
                    b.HasOne("Jornada.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRole_RoleId");

                    b.HasOne("Jornada.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRole_UsuarioId");
                });

            modelBuilder.Entity("Jornada.Models.Depoimento", b =>
                {
                    b.Navigation("DepoimentoFotos");
                });

            modelBuilder.Entity("Jornada.Models.Destino", b =>
                {
                    b.Navigation("DestinoFotos");
                });

            modelBuilder.Entity("Jornada.Models.Foto", b =>
                {
                    b.Navigation("DepoimentoFotos");

                    b.Navigation("DestinoFotos");
                });

            modelBuilder.Entity("Jornada.Models.Usuario", b =>
                {
                    b.Navigation("Depoimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
